# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Azure_secrets_group

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'  # Lokalizacja aplikacji (np. '/' dla głównego katalogu)
    output_location: 'dist'  # Lokalizacja wynikowa (np. 'build' dla Create React App)
    verbose: true
    azure_static_web_apps_api_token: $(default_Azure_Static_Web_App_deployment_token)  # Token wdrożenia
  displayName: 'Deploy to Azure Static Web App'